[environment]
    path = "./hdri/rural_asphalt_road_4k.hdr"

[objects]
    [objects.bistro]
    path = "./gltf/bistro/bistro.gltf"

[instances]
    [instances.bistro]
    object = "bistro"

[lights]
    [lights.sun]
    type = "directional"
    direction = [0.1, -1.0, 0.1]
    intensity = [5.0, 5.0, 5.0]