[environment]
    # path = "./hdri/kloppenheim_05_puresky_4k.hdr"
    color = [0.584, 0.49, 0.937]

[objects]
    [objects.helmet]
    path = "./gltf/damaged_helmet/DamagedHelmet.gltf"

    [objects.mosquito]
    path = "./gltf/mosquito/MosquitoInAmber.gltf"


[instances]
    [instances.helmet]
    object = "helmet"
    rotation = [45.0, 0.0, 0.0]
    
    [instances.mosquito]
    object = "mosquito"
    position = [2.0, 0.0, 0.0]
    scale = [100.0, 100.0, 100.0]
    rotation = [90.0, 0.0, 0.0]