[environment]
    path = "./hdri/rural_asphalt_road_4k.hdr"
    # path = "./hdri/moonless_golf_4k.hdr"
    # path = "./hdri/kloppenheim_05_puresky_4k.hdr"

[objects]
    [objects.sponza]
    path = "./gltf/sponza/Sponza.gltf"

[instances]
    [instances.sponza]
    object = "sponza"

[lights]
    # [lights.sun]
    # type = "directional"
    # direction = [0.1, -1.0, 0.1]
    # intensity = [1.0, 1.0, 1.0]