[environment]
    path = "./hdri/rural_asphalt_road_4k.hdr"

[objects]
    [objects.sponza]
    path = "./gltf/sponza/Sponza.gltf"

[instances]
    [instances.sponza]
    object = "sponza"

[lights]
    [lights.sun]
    type = "directional"
    direction = [0.0, -1.0, 0.0]
    intensity = [25.0, 25.0, 25.0]