[meshes]
    [meshes.plane]
    path = "scenes/obj/plane.obj"

    [meshes.sphere]
    path = "scenes/obj/sphere.obj"

[textures]
    [textures.schosch]
    path = "scenes/textures/test.png"

    [textures.sus]
    path = "scenes/textures/amogus.png"

[instances]
    # [instances.floor]
    # mesh = "plane"

    [instances.sphere]
    mesh = "sphere"
    position = [-1.5, 2.0, 0.0]
    texture = "sus"

    [instances.other]
    mesh = "sphere"
    position = [1.5, 2.0, 0.0]
    texture = "sus"