[meshes]
    [meshes.plane]
    path = "./obj/plane.obj"

    [meshes.sphere]
    path = "./obj/sphere.obj"

[textures]
    [textures.schosch]
    path = "./textures/test.png"

    [textures.sus]
    path = "./textures/amogus.png"

    [textures.checker]
    path = "./textures/checker.png"

[materials]
    [materials.lambertian]
    path = "./shaders/spirv/material_lambertian.spv"

    [materials.mirror]
    path = "./shaders/spirv/material_mirror.spv"

    [materials.light]
    path = "./shaders/spirv/material_light.spv"

    [materials.phong]
    path = "./shaders/spirv/material_phong.spv"

    [materials.glass]
    path = "./shaders/spirv/material_glass.spv"

[instances]
    [instances.wallLeft]
    mesh = "plane"
    position = [1.0, 0.0, 0.0]
    rotation = [0.0, 0.0, 90.0]
    texture = "checker"
    material = "lambertian"

    [instances.wallRight]
    mesh = "plane"
    position = [-1.0, 0.0, 0.0]
    rotation = [0.0, 0.0, -90.0]
    texture = "checker"
    material = "lambertian"

    [instances.wallBack]
    mesh = "plane"
    position = [0.0, 0.0, 1.0]
    rotation = [-90.0, 0.0, 0.0]
    texture = "checker"
    material = "mirror"

    # [instances.wallFront]
    # mesh = "plane"
    # position = [0.0, 0.0, -1.0]
    # rotation = [90.0, 0.0, 0.0]
    # texture = "checker"
    # material = "mirror"

    [instances.wallTop]
    mesh = "plane"
    position = [0.0, 1.0, 0.0]
    rotation = [0.0, 0.0, 180.0]
    texture = "checker"
    material = "lambertian"

    [instances.wallFloor]
    mesh = "plane"
    position = [0.0, -1.0, 0.0]
    rotation = [0.0, 0.0, 0.0]
    texture = "checker"
    material = "lambertian"

    [instances.sphere]
    mesh = "sphere"
    position = [0.0, 0.0, 0.0]
    scale = [0.2, 0.2, 0.2]
    texture = "sus"
    material = "light"

    [instances.sphere2]
    mesh = "sphere"
    position = [0.0, -0.5, 0.3]
    scale = [0.2, 0.2, 0.2]
    texture = "sus"
    material = "glass"
