[environment]
    #path = "./hdri/kloppenheim_05_puresky_4k.hdr"
    # path = "./hdri/studio_small_03_4k.hdr"
    # path = "./hdri/vestibule_4k.hdr"
    # path = "./hdri/rural_asphalt_road_4k.hdr"
    path = "./hdri/moonless_golf_4k.hdr"

[objects]
    [objects.test]
    path = "./gltf/damaged_helmet/DamagedHelmet.gltf"

    # [objects.test]
    # path = "./gltf/metal_rough_spheres/MetalRoughSpheres.gltf"

    # [objects.test]
    # path = "./gltf/sponza/Sponza.gltf"

    # [objects.test]
    # path = "./gltf/transmission_test/TransmissionTest.gltf"

    # [objects.test]
    # path = "./gltf/round_table/round_wooden_table_01_8k.gltf"

    [objects.test3]
    path = "./gltf/marble_bust/marble_bust_01_8k.gltf"

    # [objects.test]
    # path = "./gltf/mosquito/MosquitoInAmber.gltf"

    # [objects.test]
    # path = "./gltf/normal_tangent_test/NormalTangentTest.gltf"

    [objects.test2]
    path = "./gltf/round_table/round_wooden_table_01_8k.gltf"

[instances]
    [instances.test]
    object = "test"
    scale = [0.1, 0.1, 0.1]
    position = [0.0, 0.1, 0.0]

    [instances.test2]
    object = "test2"
    position = [0.0, -1.0, 0.0]

    # [instances.test1]
    # object = "test2"
    # position = [2.0, 0.0, 0.0]

    # [instances.test2]
    # object = "test"
    # position = [4.0, 0.0, 0.0]

    [instances.test3]
    object = "test3"
    position = [0.5, 0.0, 0.0]

    # [instances.test4]
    # object = "test2"
    # position = [2.0, 2.0, 0.0]

    # [instances.test5]
    # object = "test2"
    # position = [4.0, 2.0, 0.0]

[lights]
    [lights.test]
    position = [1.0, 1.0, 0.0]
    intensity = [10.0, 10.0, 10.0]

    # [lights.test2]
    # position = [-1.0, 2.0, 3.0]
    # intensity = [50.0, 50.0, 80.0]