[environment]
    path = "./hdri/vestibule_4k.hdr"

[objects]
    [objects.test]
    path = "./gltf/damaged_helmet/DamagedHelmet.gltf"

    # [objects.test]
    # path = "./gltf/transmission_test/TransmissionTest.gltf"

[instances]
    [instances.test]
    object = "test"