[meshes]
    [meshes.plane]
    path = "scenes/obj/plane.obj"

    [meshes.sphere]
    path = "scenes/obj/sphere.obj"

[textures]
    [textures.schosch]
    path = "scenes/textures/test.png"

    [textures.sus]
    path = "scenes/textures/amogus.png"

    [textures.checker]
    path = "scenes/textures/checker.png"

[instances]
    
    [instances.sphere]
    mesh = "plane"
    position = [0.0, 0.0, 0.0]
    texture = "checker"

    [instances.other]
    mesh = "sphere"
    position = [0.0, 2.0, 0.0]
    texture = "sus"
