[objects]
    #[objects.bust]
    #path = "./gltf/marble_bust/marble_bust_01_8k.gltf"

    # [objects.vase]
    # path = "./gltf/brass_vase/brass_vase_03_4k.gltf"

    [objects.table]
    path = "./gltf/round_table/round_wooden_table_01_8k.gltf"

    #[objects.test]
    #path = "./gltf/test/test.gltf"

[instances]
    #[instances.bust]
    #object = "bust"

    [instances.table]
    object = "table"
    position = [0.0, -1.0, 0.0]

    # [instances.vase]
    # object = "vase"
    # position = [0.5, 0.0, 0.0]
    # scale = [2.5, 2.5, 2.5]

    #[instances.test]
    #object = "test"