[environment]
    #path = "./hdri/kloppenheim_05_puresky_4k.hdr"
    path = "./hdri/studio_small_03_4k.hdr"
    # path = "./hdri/vestibule_4k.hdr"
    # path = "./hdri/rural_asphalt_road_4k.hdr"
    # path = "./hdri/moonless_golf_4k.hdr"

[objects]
    [objects.test]
    path = "./gltf/transmission_test/TransmissionTest.gltf"

[instances]
    [instances.test]
    object = "test"

[lights]
    # [lights.test0]
    # type = "point"
    # position = [0.0, 3.0, 3.0]
    # intensity = [5000.0, 5000.0, 5000.0]