[environment]
    color = [0.584, 0.49, 0.937]
    # path = "./hdri/kloppenheim_05_puresky_4k.hdr"

[objects]
    [objects.test]
    path = "./gltf/transmission_test/TransmissionTest.gltf"

[instances]
    [instances.test]
    object = "test"