#version 460 core
#extension GL_EXT_ray_tracing : enable

~include "shaders/common.glsl"
~include "shaders/random.glsl"
~include "shaders/payload.glsl"
~include "shaders/texture_data.glsl"

layout(location = 0) callableDataInEXT MaterialPayload material_payload;


void main() {
    material_payload.surface_color = vec3(1.0);
    material_payload.emission = vec3(0);

    material_payload.direction = reflect(material_payload.direction, material_payload.normal);
}