#version 460 core
#extension GL_EXT_ray_tracing : enable

~include "shaders/payload.glsl"
~include "shaders/texture_data.glsl"

layout(location = 0) callableDataInEXT MaterialPayload material_payload;

void main() {
    material_payload.surface_color = sample_texture(material_payload.instance, material_payload.uv);
    material_payload.direction = reflect(material_payload.direction, material_payload.normal);
}