#ifndef INC_INTERFACE_RT
#define INC_INTERFACE_RT

#define ENABLE_DIRECT_LIGHTING 1
#define ENABLE_INDIRECT_LIGHTING 2
#define ENABLE_RESTIR 4

#define DESCRIPTOR_SET_FRAMEWORK 0
#define DESCRIPTOR_SET_OBJECTS 1
#define DESCRIPTOR_SET_CUSTOM 2

// framework data bindings
#define DESCRIPTOR_BINDING_ACCELERATION_STRUCTURE 0
#define DESCRIPTOR_BINDING_CAMERA_PARAMETERS 1
#define DESCRIPTOR_BINDING_OUTPUT_BUFFERS 2
#define DESCRIPTOR_BINDING_LIGHTS 3
#define DESCRIPTOR_BINDING_RESTIR_RESERVOIRS 4

// mesh data bindings
#define DESCRIPTOR_BINDING_MESH_INDICES 0
#define DESCRIPTOR_BINDING_MESH_VERTICES 1
#define DESCRIPTOR_BINDING_MESH_NORMALS 2
#define DESCRIPTOR_BINDING_MESH_TEXCOORDS 3
#define DESCRIPTOR_BINDING_MESH_TANGENTS 4
#define DESCRIPTOR_BINDING_MESH_DATA_OFFSETS 5
#define DESCRIPTOR_BINDING_MESH_OFFSET_INDICES 6

// material data bindings
#define DESCRIPTOR_BINDING_TEXTURES 7
#define DESCRIPTOR_BINDING_TEXTURE_INDICES 8
#define DESCRIPTOR_BINDING_MATERIAL_PARAMETERS 9

// output image indices
#define OUTPUT_IMAGE_RESULT 0
#define OUTPUT_IMAGE_ACCUMULATED 1
#define OUTPUT_IMAGE_ALBEDO 2
#define OUTPUT_IMAGE_NORMAL 3
#define OUTPUT_IMAGE_INSTANCE 4
#define OUTPUT_IMAGE_INSTANCE_COLOR 5
#define OUTPUT_IMAGE_ROUGHNESS 6
#define OUTPUT_IMAGE_RAY_DEPTH 7
#define OUTPUT_IMAGE_ENVIRONMENT_CDF 8
#define OUTPUT_IMAGE_ENVIRONMENT_CONDITIONAL 9

#include "structs.glsl"

#endif